### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pke** [ubahnverleih/simple-opening-hours#1]
Nice and simple approach. Care to add some tests?

**Comment by ubahnverleih** [comment]
is on my todolist :)

**Comment by pke** [comment]
I started with some test in my fork
https://github.com/pke/simple-opening-hours/commits/feature/add-tests

It also improves the 24/7 handling and parse times with less `replace` calls

**Comment by pke** [comment]
No tests yet? Well, my branch has, so I am closing this stale issue.

**Comment by ubahnverleih** [comment]
feel free to open a pull request

**Comment by pke** [comment]
you right, just did that. My branch was still laying around.
